### ISSUE TITLE
Configuring mini buffer display

### ISSUE THREAD

**Issue by unlaered** [jrosdahl/iflipb#1]
Is there a way to customize how the buffer list appears in the mini buffer? I think more visual differentiation would be a good idea, maybe by customizing separators, colors, word space, etc.

**Comment by jrosdahl** [comment]
Hi,

No, there's currently no way to customize it. What would you like the appearance to be?

**Comment by unlaered** [comment]
This is a very useful package!

I think it would be ideal if the selected buffer could be made to stand out more from the buffer list. The parentheses and bold face are a start. How about making the selection stand out with a color? Or dimming the other buffer names? Or allowing the space within the list to be configured?

Thanks!

**Comment by jrosdahl** [comment]
I wouldn't be against configurability, but I don't really have time or interest to work on it for the time being. Patches are welcome.
