### ISSUE TITLE
iflipb-current-buffer-face appears in Ibuffer

### ISSUE THREAD

**Issue by ktfleming** [jrosdahl/iflipb#14]
Steps to reproduce:

1. Call `iflip-next-buffer` to make some buffer the current iflipb buffer
2. `M-x ibuffer`

After doing so, the name of the current iflipb buffer will be shown using `iflipb-current-buffer-face` inside Ibuffer. I've been able to reproduce this on Emacs 28.1, with iflip as the only external package installed.

**Comment by jrosdahl** [comment]
Thanks for the bug report! Will fix.
