### ISSUE TITLE
Atomic vs. Iterative iflipb-next-buffer

### ISSUE THREAD

**Issue by der-daniel** [jrosdahl/iflipb#2]
Hi,

I really love the package.
I have a improvement request as similarly discussed in the Wiki: https://www.emacswiki.org/emacs/iflipb

*atomic flip*
I want to be able to switch between the two most recently used buffers by pressing `C-tab` and then releasing both key.
Then if I hit `C-tab` again I get back to the before buffer.

*iterative flip*
Holding down `C` and pressing `tab` repeatedly I can switch between all last recently used buffer.

At the moment I have something like this:

    (defun iflipb-atomic-flip () 
      (interactive) 
      (iflipb-next-buffer nil) 
      (iflipb-select-buffer 1))
     
    (bind-key* "C-`" 'iflipb-atomic-flip)
    (bind-key* "<C-tab>" 'iflipb-next-buffer)
    (bind-key* "<C-iso-lefttab>" 'iflipb-previous-buffer)

Do you see a way to combining them into a general `C-tab`?

~ For Frodo

**Comment by jrosdahl** [comment]
There is [no Emacs support for key up/down events](https://emacs.stackexchange.com/questions/10468/why-doesnt-emacs-support-key-up-down-events), so it's unfortunately not possible to implement the behavior you suggest.

**Comment by der-daniel** [comment]
Ok, I see...
Than I will stick to my solution. :+1:
