### ISSUE TITLE
new buffers are appended to the end, not the start

### ISSUE THREAD

**Issue by bgwines** [jrosdahl/iflipb#7]
hi, there!

I'm relatively new to emacs so if you have an tips for how I can debug this kind of thing on my own in the future I'd love to hear your input :)

when I open a file, replacing the currently opened file in my emacs buffer - either with `C-x C-f` (`spacemacs/helm-find-files`) or with `helm-projectile-find-file`, it becomes the **last** file in my iflipb stack. That is to say, if I am viewing file *A*, open file *B*, then execute `iflipb-next-buffer`, it takes me to the file before *A*, and then `iflip-previous-buffer` takes me back to *A*. But *B* is way back at the end.

thanks so much for your help :):)

**Comment by bgwines** [comment]
ah, further testing reveals that only the keyboard shortcuts (for me, `M-n` and `M-o`) trigger this behavior. Running the commands via `M-x` triggers the expected behavior, so this probably isn't a bug in your package... I wonder if I need to configure it differently somehow?

**Comment by bgwines** [comment]
interestingly, a different assignment (`C-\'` instead of `M-n`) triggers the same behavior

**Comment by bgwines** [comment]
hmm, tried a brand new `.spacemacs` file and the same issue happens. Wild.

**Comment by jrosdahl** [comment]
Hi there, I have no specific hints I'm afraid. Not a Spacemacs user myself.

**Comment by bgwines** [comment]
no worries :) I'll keep digging. Closing this issue -- thanks for chiming in; was worth a shot
