### ISSUE TITLE
Allow user to execute kill-buffer without resetting iflipb state

### ISSUE THREAD

**Issue by archenemies** [jrosdahl/iflipb#8]
Where it says:

    (not (or (eq last-command 'iflipb-next-buffer)
              (eq last-command 'iflipb-previous-buffer))))

I found it useful to change it to this:

    [ something that also checks if last-command is kill-buffer ]

This facilitates cleaning up my buffer list, since I often see a buffer I don't need anymore when I cycle the list using iflipb. With my improvement, I can kill it without losing my place in the list.

(Edited: the first version of the above code was incorrect, but please see below)

**Comment by archenemies** [comment]
I'm not sure why I thought this worked, but it is not working now. And I see that `last-command` is supposed to be a global. My apologies for the premature contribution.

**Comment by archenemies** [comment]
I now have a working version of this idea, that lets me intersperse kill-buffer with iflipb commands. However, it is modified from iflipb.el from 2014, and I should upgrade to the recent iflipb to take advantage of "iflipb now puts the current frame's recent buffers first".

**Comment by archenemies** [comment]
I'm attaching a patch against the current version of `iflipb.el`. It's in need of editing, and I'm not sure if it implements features that others want. I wanted to update to the latest iflipb version for myself anyway, so there wasn't much extra work to generate a patch.

It implements the following changes:

- Exclude buffers from iflipb list which are visible but not focused

- Fix a bug I encountered in "iflipb-format-buffer" where "add-text-properties" results in an error

        Debugger entered--Lisp error: (error "Attempt to modify read-only object" "*GNU Emacs*")
          add-text-properties(0 11 (face iflipb-current-buffer-face) "*GNU Emacs*")

  I decided that I don't need the text to be bold, but probably a better fix should be implemented which keeps the fancy text properties.

- Provides a new version of the "kill-buffer" function, which doesn't reset the iflipb state. Users can bind this to "C-x k" and this makes it a little easier to clean up the buffer list while you are going through it. Otherwise if you want to kill buffer 10, buffer 11, buffer 12, but visit buffer number 13, then you have about 20 keystrokes to type, whereas now you can do it with 3 or 6 depending on how you count.

- Added a function "iflipb-switch-buffer". It switches back and forth between the two most recent buffers. In the past I had C-x C-x bound as follows:

        (global-set-key "\C-x\C-x" '(lambda () (interactive) (switch-to-buffer (other-buffer))))

  The new function does much the same thing, but using iflipb. It saves a bit of typing and thinking. I guess "C-x C-x" is bound to "exchange-point-and-mark" by default, so I'm not sure what other people would bind it to. It can also be used to choose the current selection when navigating the buffer list using iflipb.

        (defun iflipb-switch-buffer ()
          (interactive)
          (setq last-command nil)
          (iflipb-next-buffer nil))

Here it is: [iflipb.patch.txt](https://github.com/jrosdahl/iflipb/files/4729616/iflipb.patch.txt)

**Comment by jrosdahl** [comment]
Thanks. It's a bit of work to disect the patch into appliable parts, but here are some comments:

> * Exclude buffers from iflipb list which are visible but not focused

Sounds good to have, but I would suggest to make the behavior opt-in.

> * Fix a bug I encountered in "iflipb-format-buffer" where "add-text-properties" results in an error
>   ```
>     Debugger entered--Lisp error: (error "Attempt to modify read-only object" "*GNU Emacs*")
>       add-text-properties(0 11 (face iflipb-current-buffer-face) "*GNU Emacs*")
>   ```

I've never seen that bug. Which Emacs version?

> * Provides a new version of the "kill-buffer" function, which doesn't reset the iflipb state. Users can bind this to "C-x k" and this makes it a little easier to clean up the buffer list while you are going through it. Otherwise if you want to kill buffer 10, buffer 11, buffer 12, but visit buffer number 13, then you have about 20 keystrokes to type, whereas now you can do it with 3 or 6 depending on how you count.

I like the idea. How about using `(call-interactively #'kill-buffer)` instead of `(apply 'kill-buffer args)` so that it's actually the same interactive behavior as for the `kill-buffer` command? I.e. something like this:

```diff
--- a/iflipb.el
+++ b/iflipb.el
@@ -297,8 +297,7 @@ This is the original order of buffers to the left of
 
 (defun iflipb-first-iflipb-buffer-switch-command ()
   "Determine if this is the first iflipb invocation this round."
-  (not (or (eq last-command 'iflipb-next-buffer)
-           (eq last-command 'iflipb-previous-buffer))))
+  (not (string-match "^iflipb-" (symbol-name last-command))))
 
 (defun iflipb-restore-buffers ()
   "Helper function that restores the buffer list to the original state."
@@ -383,6 +382,18 @@ buffer list."
     (iflipb-select-buffer (1- iflipb-current-buffer-index)))
   (setq last-command 'iflipb-previous-buffer))
 
+;;;###autoload
+(defun iflipb-kill-buffer ()
+  "Same as `kill-buffer' but keep the iflipb buffer list state."
+  (interactive)
+  (call-interactively #'kill-buffer)
+  (if (iflipb-first-iflipb-buffer-switch-command)
+      (setq last-command 'kill-buffer)
+    (if (< iflipb-current-buffer-index (length (iflipb-interesting-buffers)))
+        (iflipb-select-buffer iflipb-current-buffer-index)
+      (iflipb-select-buffer (1- iflipb-current-buffer-index)))
+    (setq last-command 'iflipb-kill-buffer)))
+
 (provide 'iflipb)
 
 ;;; iflipb.el ends here
```

> * Added a function "iflipb-switch-buffer"

That feels like too much of a special case.

**Comment by archenemies** [comment]
Your version looks good to me.

Thanks for the tip about `call-interactively`, I couldn't figure out how to do that.

**Comment by jrosdahl** [comment]
Committed to master now.
